name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cypress-run:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
